### ISSUE TITLE
PRACTICA_4

### ISSUE THREAD

**Issue by IsaacCS1** [SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-tadp-isag#1]
[PRACTICA_4.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-tadp-isag/files/8348013/PRACTICA_4.pdf)

**Comment by IrvingFernand0** [comment]
Esta práctica obtuvo 100%
Correspondiente a **20** de calificación

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
